export const environment = {
  production: true,
  name: 'local',
  settings: {
    'showWidgetIcon': true,
    'ocelotApiGatewayBaseUrl': '',
    'staffingAuthenticationApiBaseUrl': '',
    'resourcesApiBaseUrl': '',
    'pegC2COpportunityDetailsUrl':'',
    'launchDarklyClientId': '',
    'projectsPageSize': 60,
    'resourcesPerPage': 50,
    'scrollDistance': 3,
    'googleAnalyticsJqueryUrl': '',
    'googleAnalyticsJsUrl': '',
    'googleAnalyticsProfileUrl': '',
    'tableauStaffingAllocationReportUrl': '',
    'tableauStaffingAllocationsMonthlyReportUrl': '',
    'tableauHistoricalAllocationsForPromotionsUrl':'',
    'tableauAvailabilityReportUrl': '',
    'tableauIndividualResourceDetailsReportUrl': '',
    'tableauWeeklyDeploymentSummaryReportUrl': '',
    'tableauMonthlyDeploymentReportUrl': '',
    'tableauFTEUtilizationReportUrl':'',
    'tableauFTEUtilizationIndividualReportUrl':'',
    'tableauDailyCapacityReportUrl': '',
    'tableauCapacityPlanningCaseViewReportUrl': '',
    'tableauResourceAllocationsTodayReportUrl': '',
    'tableauRingfenceStaffingReportUrl': '',
    'tableauOverAllocatedAuditReportUrl': '',
    'tableauAllocatedWhileOnLOAAuditReportUrl': '',
    'tableauCaseUpdatesAuditReportUrl': '',
    'tableauCapacityBreakdownReportUrl': '',
    'tableauPriceRealizationUrl': '',
    'tableauResourceAllocationsUrl': '',
    'tableauMonthlyPracticeAreaStaffingUrl': '',
    'tableauCommitmentDetailsUrl': '',
    'clearLocalStorage': 'false',
    'siteUnderMaintainance': 'false',
    'environmentUrl': '',
    'tableauTimeInLaneReportUrl': '',
    'tableauPracticeStaffingCaseServedReportUrl': '',
    'tableauAffiliateTimeInPracticeReportUrl': '',
    'tableauCaseEconomicsReportUrl': '',
    'tableauCaseEconomicsNonBillableReportUrl':'',
    'tableauWhoWorkedWithWhomReportUrl':'',
    'tableauWhoSMAPAllocationsReportUrl':'',
    'tableauCaseExperienceReportUrl':'',
    'globalStaffingSupportMailbox': '',
    'externalNavParameters': '',
    "instrumentationKey": '',
    "monthCloseDay":25
  },
  imageExtensions: ['.png', '.jpeg'],
  azureActiveDirectorySettings:{
    enableAAD: false,
    staffing_automation_testing_username: "",
    clientId:"",
    tenantId:"",
    redirectUri:""
  },
  resourcesApiConfig:{
    subscriptionKey:"",
    version: ""
  }
};
